Modules/Transaction/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['impersonate', 'auth'])->group(function () {
   Route::get('/billing', 'TransactionController@view')->name('billing.view');
    Route::name('transaction.')->prefix('transaction')->group(function () {
        Route::get('open_invoices_report', 'TransactionController@openInvoices')->name('open_invoices_report');
        Route::get('overdue_invoices_report', 'TransactionController@overdueInvoices')->name('overdue_invoices_report');
        Route::get('payments_received_report', 'TransactionController@receivedPayment')->name('payments_received_report');

        Route::name('quotation_material.')->prefix('quotation_material')->namespace('QuotationMaterial')->group(function () {
            Route::get('view', 'ViewController')->name('view');
            Route::put('/{id}', 'QuotationMaterialController@update')->name('update');
            Route::resource('/', 'QuotationMaterialController');
            Route::get('/{id}/detail', 'QuotationMaterialController@detail')->name('detail');
            Route::get('/export', 'QuotationMaterialController@export')->name('export');
            Route::get('/{id}/edit', 'QuotationMaterialController@edit')->name('edit');
            Route::get('/{id}/show', 'QuotationMaterialController@show')->name('show');
            Route::get('/{id}/pdf', 'QuotationMaterialController@pdf')->name('pdf');
            Route::delete('/{id}', 'QuotationMaterialController@destroy')->name('destroy');
            Route::post('attachment','QuotationMaterialController@saveAttachment')->name('attachment');

            Route::get('/tax', 'QuotationMaterialController@tax')->name('tax');
            Route::get('/product_price/{id}', 'QuotationMaterialController@productPrice')->name('product_price');
            Route::get('/product_detail/{id}/{productId}', 'QuotationMaterialController@productDetail')->name('product_detail');
            Route::get('/salesman', 'QuotationMaterialController@salesman')->name('salesman');
            Route::get('/paymentTerm', 'QuotationMaterialController@paymentTerm')->name('paymentTerm');
            Route::get('/customer', 'QuotationMaterialController@customer')->name('customer');
             Route::get('/customer-detail/{id}', 'QuotationMaterialController@customerDetail')->name('customer');
            Route::get('/salesmenId', 'QuotationMaterialController@salesmenId')->name('salesmenId');

            Route::resource('approval', 'QuotationMaterialApprovalController');
            Route::put('approval/update_item/{id}', 'QuotationMaterialApprovalController@updateItem')->name('approval.update_item');

            Route::resource('report', 'QuotationMaterialReportController');
        });

        Route::name('sales_order.')->prefix('sales_order')->namespace('SalesOrder')->group(function () {
            Route::get('view', 'ViewController')->name('view');
            Route::post('/store', 'SalesOrderController@store')->name('store');
            Route::resource('/', 'SalesOrderController');
            Route::get('/export', 'SalesOrderController@export')->name('export');
            Route::get('/{id}/detail', 'SalesOrderController@detail')->name('detail');
            Route::get('/{id}/print', 'SalesOrderController@print')->name('print');
            Route::get('/{id}/edit', 'SalesOrderController@edit')->name('edit');
            Route::get('/{id}/show', 'SalesOrderController@show')->name('show');
            Route::put('/{id}', 'SalesOrderController@update')->name('update');
            Route::post('attachment','SalesOrderController@saveAttachment')->name('attachment');
             Route::get('/customer-detail-sales/{id}', 'SalesOrderController@customerDetail')->name('customer-detail-sales');

            Route::delete('/{id}', 'SalesOrderController@destroy')->name('destroy');

            Route::get('/currency', 'SalesOrderController@currency')->name('currency');
            Route::get('/quotation_material', 'SalesOrderController@quotationMaterial')->name('quotation_material');
            Route::get('/quotation_material_first', 'SalesOrderController@quotationMaterialFirst')->name('quotation_material_first');
            Route::get('/fetch_quotation_material_item', 'SalesOrderController@fetchQuotationMaterialItem')->name('fetch_quotation_material_item');

            Route::resource('approval', 'SalesOrderApprovalController');
            Route::put('approval/update_item/{id}', 'SalesOrderApprovalController@updateItem')->name('approval.update_item');

            Route::resource('report', 'SalesOrderReportController');
            Route::get('sales-order-report', 'SalesOrderController@report')->name('sales-order-report');
            Route::get('/{id}/report-detail', 'SalesOrderController@detailReport')->name('report-detail');
            Route::get('/pdf/{id}', 'SalesOrderReportController@pdf')->name('pdf');

            Route::get('/download-excel/', 'SalesOrderReportController@export')->name('export');

        });
        Route::name('delivery_order_material.')->prefix('delivery_order_material')->namespace('DeliveryOrderMaterial')->group(function () {
            Route::get('view', 'ViewController')->name('view');
            Route::resource('/', 'DeliveryOrderMaterialController');
            Route::get('/outstanding', 'DeliveryOrderMaterialController@outstanding')->name('outstanding');
            Route::get('/export', 'DeliveryOrderMaterialController@export')->name('export');
            Route::get('/{id}/detail', 'DeliveryOrderMaterialController@detail')->name('detail');
            Route::get('/{id}/pdf', 'DeliveryOrderMaterialController@pdf')->name('pdf');
            Route::get('/{id}/edit', 'DeliveryOrderMaterialController@edit')->name('edit');
            Route::get('/{id}/show', 'DeliveryOrderMaterialController@show')->name('show');
            Route::put('/{id}', 'DeliveryOrderMaterialController@update')->name('update');
            Route::post('attachment','DeliveryOrderMaterialController@saveAttachment')->name('attachment');

            Route::delete('/{id}', 'DeliveryOrderMaterialController@destroy')->name('destroy');

            Route::get('/sales_order_material', 'DeliveryOrderMaterialController@salesOrderMaterial')->name('sales_order_material');
            Route::get('/warehouse', 'DeliveryOrderMaterialController@warehouse')->name('warehouse');
            Route::get('/sales_order_material_item', 'DeliveryOrderMaterialController@salesOrderMaterialItem')->name('sales_order_material_item');

            Route::resource('approval', 'DeliveryOrderMaterialApprovalController');
            Route::put('approval/update_item/{id}', 'DeliveryOrderMaterialApprovalController@updateItem')->name('approval.update_item');
            Route::get('delivery-order-report', 'DeliveryOrderMaterialController@report')->name('delivery-order-report');
            Route::get('/{id}/report-detail', 'DeliveryOrderMaterialController@detailReport')->name('report-detail');

        });

        Route::name('credit_note.')->prefix('credit_note')->group(function() {
            Route::resource('/', 'CreditNoteController');
            Route::get('/{id}/edit', 'CreditNoteController@edit')->name('edit');
            Route::put('/{id}', 'CreditNoteController@update')->name('update');
            Route::post('transaction/credit-note/receivable', 'CreditNoteController@getReceivable')->name('getReceivable');
            Route::delete('/{id}', 'CreditNoteController@destroy')->name('destroy');
            Route::get('report', 'CreditNoteController@report')->name('report');
            Route::get('detail/{id}', 'CreditNoteController@reportDetail')->name('report-detail');
        });

        Route::name('ar_credit_debit_note.')->prefix('ar_credit_debit_note')->group(function() {
            Route::resource('/', 'ARCreditDebitNoteController');
            Route::get('/{id}/edit', 'ARCreditDebitNoteController@edit')->name('edit');
            Route::put('/{id}', 'ARCreditDebitNoteController@update')->name('update');
            Route::post('transaction/ar-credit-debit-note/receivable', 'ARCreditDebitNoteController@getReceivable')->name('getReceivable');
            Route::delete('/{id}', 'ARCreditDebitNoteController@destroy')->name('destroy');
            Route::get('report', 'ARCreditDebitNoteController@report')->name('report');
            Route::get('detail/{id}', 'ARCreditDebitNoteController@reportDetail')->name('report-detail');
        });

        Route::resource('sales-return', 'SalesReturnController');
        Route::get('sales-return-report', 'SalesReturnController@report')->name('sales-return-report');
        Route::get('sales-return-detail/{id}', 'SalesReturnController@reportDetail')->name('sales-return-report-detail');
    });
});

Modules/Transaction/Entities/DeliveryOrderMaterial.php
<?php

namespace Modules\Transaction\Entities;

use Modules\HR\Entities\Employee;
use Modules\HR\Entities\Department;
use Modules\Procurement\Entities\Tax;
use Illuminate\Database\Eloquent\Model;
use Modules\Procurement\Entities\Customer;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Procurement\Entities\PaymentTerm;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class DeliveryOrderMaterial extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    protected $guarded = [];

    public function scopeApproved($query)
    {
        return $query->where('status', 'approved');
    }

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function salesOrder()
    {
        return $this->belongsTo(SalesOrder::class);
    }

    public function salesman()
    {
        return $this->belongsTo(Employee::class);
    }

    public function paymentTerm()
    {
        return $this->belongsTo(PaymentTerm::class);
    }

    public function items()
	{
		return $this->hasMany(DeliveryOrderMaterialItem::class, 'delivery_order_material_id');
	}

    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function latestApprove()
    {
        return $this->belongsTo(Employee::class, 'latest_approver');
    }

    public function approveToGo()
    {
        return $this->belongsTo(Employee::class, 'approver_to_go');
    }

    public function rejectedBy()
    {
        return $this->belongsTo(Employee::class, 'rejected_by');
    }
}

Modules/Transaction/Http/Controllers/Api/DeliveryOrderMaterialController.php
<?php

namespace Modules\Transaction\Http\Controllers\Api;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;

use Modules\Transaction\Entities\DeliveryOrderMaterial;
use Modules\Transaction\Entities\DeliveryOrderMaterialItem;
use Modules\Transaction\Entities\SalesOrderItem;

class DeliveryOrderMaterialController extends Controller
{
    public function edit($id)
	{
		return DeliveryOrderMaterial::with(['department','customer', 'salesman', 'paymentTerm', 'salesOrder', 'items', 'items.salesOrderMaterialItem.product', 'items.salesOrderMaterialItem.uom', 'items.warehouse'])->find($id);
	}

    public function getItem($id)
    {
        $row = DB::select("select dis.* from sales_orders so
        inner join delivery_order_materials dos on dos.sales_order_id = so.id
        inner join delivery_order_material_items dis on dis.delivery_order_material_id = dos.id
        where so.id = $id" );

        return $row;
    }

    public function removeItem($id)
	{
        $row = DeliveryOrderMaterialItem::find($id);
        $salesOrderItem = SalesOrderItem::find($row->sales_order_item_id);
        $salesOrderItem->delivered_qty = $salesOrderItem->delivered_qty + $row->qty;
        $salesOrderItem->save();
        DeliveryOrderMaterial::where('sales_order_id', $salesOrderItem->sales_order_id)->update(['status_partial' => 0]);
        $row->forceDelete();
		return response()->json([
			'success' => true
		]);
	}
}

Modules/Transaction/Http/Controllers/DeliveryOrderMaterial/DeliveryOrderMaterialApprovalController.php
<?php

namespace Modules\Transaction\Http\Controllers\DeliveryOrderMaterial;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Modules\HR\Entities\Employee;
use Modules\Transaction\Entities\DeliveryOrderMaterial;
use Modules\Transaction\Entities\DeliveryOrderMaterialItem;
use Modules\Transaction\Entities\DeliveryOrderMaterialApproval;
use Modules\Transaction\DataTables\DeliveryOrderMaterialApprovalDatatable;

class DeliveryOrderMaterialApprovalController extends Controller
{
    public function index(DeliveryOrderMaterialApprovalDatatable $datatable)
    {
        $this->hasPermissionTo('view delivery order material approval');

        $employee = Employee::where('user_id', auth()->user()->id)->first();
        if (empty($employee)){
            flash('Ops.. please check your employee id.')->error();
            return back();
        }

        $rows = filterModuleByStatus(DeliveryOrderMaterial::class, [
            'employee', 'department', 'paymentTerm', 'salesOrder.paymentTerm', 'customer', 'salesman', 'salesOrder'
        ]);
        
        return $datatable->render('transaction::delivery_order_material.approval.index', compact('rows'));
    }


    public function show($id)
    {
        $this->hasPermissionTo('view sales order approval');

        $row = DeliveryOrderMaterial::findOrFail($id);
        $items = DeliveryOrderMaterialItem::where('delivery_order_material_id', $id)->get();
        $histories = DeliveryOrderMaterialApproval::where('delivery_order_material_id', $id)
            ->get()
            ->sortBy('id');
        if($row){
            $media = $row->getMedia('delivery_order_material') ?? [];
        }else{
            $media = [];
        }

        return view('transaction::delivery_order_material.approval.detail', compact('row', 'items','histories','media'));
    }

    public function update(Request $request, $id)
    {
        $this->hasPermissionTo('edit sales order approval');

        $description = request('description');
        if (request()->has('approve')) {
            \Approval::action(DeliveryOrderMaterial::class, DeliveryOrderMaterialApproval::class, $id, 'delivery_order_material_id', $description);
        } else {
            \Approval::reject(DeliveryOrderMaterial::class, DeliveryOrderMaterialApproval::class, $id, 'delivery_order_material_id', $description);
        }

        flash('Your data has been saved successfully')->success();
        return redirect()->route('transaction.delivery_order_material.approval.index');
    }
}

Modules/Transaction/Http/Controllers/DeliveryOrderMaterial/ViewController.php
<?php

namespace Modules\Transaction\Http\Controllers\DeliveryOrderMaterial;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class ViewController extends Controller
{
    public function __invoke()
    {
        return view('transaction::delivery_order_material.index');
    }
}

Modules/Transaction/Resources/views/delivery_order_material/entry/create.blade.php
@extends('transaction::layouts.master')

@section('transaction::title', 'Add Delivery Order')

@section('transaction::breadcrumb-2')
@include('transaction::include.breadcrum', [
'title' => 'Delivery Order',
'active' => true,
'url' => route('transaction.delivery_order_material.index')
])
@endsection
@section('transaction::breadcrumb-3')
@include('transaction::include.breadcrum', [
'title' => 'Add',
'active' => true,
'url' => route('transaction.delivery_order_material.create')
])
@endsection
@section('transaction::content')
<div class="row" id="pr-create">
    <div class="col-md-12">
        <div class="card no-b no-r">
            <div class="card-body">
                <h5 class="card-title">
                    <div class="text-right">
                        <a href="{{ route('transaction.delivery_order_material.index') }}" class="btn btn-warning">
                            <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
                        </a>
                    </div>
                </h5>
                <hr>
                <div class="row">
                    <div class="col-12">
                        @if(request()->id)
                        <delivery-order-material-create :so-id="{{request()->id}}"/>
                            @endif
                            <delivery-order-material-create/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

Modules/Transaction/Resources/views/delivery_order_material/entry/edit.blade.php
@extends('transaction::layouts.master')

@section('transaction::title', 'Edit Delivery Order')

@section('transaction::breadcrumb-2')
@include('transaction::include.breadcrum', [
'title' => 'Delivery Order',
'active' => true,
'url' => route('transaction.delivery_order_material.index')
])
@endsection
@section('transaction::breadcrumb-3')
@include('transaction::include.breadcrum', [
'title' => 'Edit',
'active' => true,
'url' => route('transaction.delivery_order_material.edit', request()->segment(3))
])
@endsection
@section('transaction::content')

<div class="row">
    <div class="col-md-12">
        <div class="card no-b no-r">
            <div class="card-body">
                <h5 class="card-title">
                    <div class="text-right">
                        <a href="{{ route('transaction.delivery_order_material.index') }}" class="btn btn-warning">
                            <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
                        </a>
                    </div>
                </h5>
                <hr>
                <div class="row">
                    <div class="col-12">
                        @if(request()->resubmit)
                        <delivery-order-material-edit :id="{{ request()->segment(3) }}" :resubmit="{{request()->resubmit}}"/>
                            @endif
                            <delivery-order-material-edit :id="{{ request()->segment(3) }}" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endsection

Modules/Transaction/Resources/views/delivery_order_material/entry/export.blade.php
<table>
  <tr style="width: 40%">
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Code Number</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Sales Order</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Date</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Customer</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Salesman</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Payment Term</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Address</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Description</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Next Approver</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Final Approver</th>
    <th style="background-color:#e2e25f; font-weight: bold;" align="center">Status</th>
  </tr>
  @foreach($rows as $row)
  <tr>
    <td>{{$row->code_number}}</td>
    <td>{{optional($row->salesOrder)->code_number}}</td>
    <td>{{format_d_month_y($row->date)}}</td>
    <td>{{optional($row->customer)->company_name}} - {{optional($row->customer)->pic_1}} - {{optional($row->customer)->pic_phone_1}} - {{optional($row->customer)->address}}</td>
    <td>{{optional($row->salesman)->name}}</td>
    <td>{{optional($row->paymentTerm)->name}}</td>
    <td>{{$row->description}}</td>
    <td>{{optional($row->approveToGo)->name}}</td>
    <td>{{optional($row->latestApprove)->name}}</td>
    <td>{{$row->status}}</td>
  </tr>
  @endforeach
</table>

Modules/Transaction/Resources/views/delivery_order_material/entry/index.blade.php
@extends('transaction::layouts.master')

@section('transaction::title', 'Delivery Order')

@section('transaction::breadcrumb-2')
    @include('transaction::include.breadcrum', [
    'title' => 'Penjualan',
    'active' => true,
    'url' => route('billing.view')
    ])
@endsection

@section('transaction::breadcrumb-3')
    @include('transaction::include.breadcrum', [
    'title' => 'Delivery Order Entry',
    'active' => true,
    'url' => route('transaction.delivery_order_material.index')
    ])
@endsection

@push('stylesheet')
    <link rel="stylesheet" href="{{ asset('css/dropify.min.css') }}">
@endpush

@section('transaction::content')
    <div class="row">
        <div class="col-12">
            @include('flash::message')
            <div class="card">
                <div class="card-body">
                    <div class="form-group pb-1">
                        <a href="{{ route('transaction.delivery_order_material.export') }}" class="tl-tip" title="Export to Excel" data-placement="left" data-original-title="Excel">
                            <img src="{{asset('images/excel.png')}}" alt="">
                        </a>
                    </div>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="document-tab"  href="{{ route('transaction.delivery_order_material.outstanding') }}" role="tab" aria-controls="outstanding" aria-selected="false">Outstanding</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        @include('transaction::delivery_order_material.entry.tab.entry')
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('javascript')
    @include('transaction::delivery_order_material.entry.modals.index')

    <script>
     $(document).on('click', '#modal_attachment', function(){
        var valId = $(this).data('id');
        $('#id_delivery_order_material').val(valId);
        var requestUrl = '{{ route('transaction.delivery_order_material.show', ':id') }}';
        var getData = requestUrl.replace(':id', valId);

          $('#attachment').modal('hide');

        $.ajax({
            url: getData,
            type: "GET",
            success: function(media) {

           $("#attachment").find('.modal-body').html(media)

            }
        });
    });
</script>
    </script>
    <script src="{{ asset('js/dropify.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.dropify').dropify();
        });
        $('.dropify').dropify();
        $('.add-image-btn').click(function() {
            var name = $(this).data('name');
            console.log(name);
            $('#' + name + '-btm').before("<div class='form-group col-md-3'><input type='file' name='" + name + "[]' id='input-file-max-fs' class='dropify' data-height='160px' data-max-file-size='20M' data-allowed-file-extensions='png jpg jpeg bmp gif pdf' /></div>");
            $('.dropify').dropify();
        });
        @include('include.dropify-remove-image')
    </script>
@endpush

Modules/Transaction/Resources/views/delivery_order_material/entry/index_outstanding.blade.php
@extends('transaction::layouts.master')

@section('transaction::title', 'Delivery Order Outstanding')

@section('transaction::breadcrumb-2')
    @include('transaction::include.breadcrum', [
    'title' => 'Penjualan',
    'active' => true,
    'url' => route('billing.view')
    ])
@endsection

@section('transaction::breadcrumb-3')
    @include('transaction::include.breadcrum', [
    'title' => 'Delivery Order Outstanding',
    'active' => true,
    'url' => route('transaction.delivery_order_material.outstanding')
    ])
@endsection

@push('stylesheet')
    <link rel="stylesheet" href="{{ asset('css/dropify.min.css') }}">
@endpush

@section('transaction::content')
    <div class="row">
        <div class="col-12">
            @include('flash::message')
            <div class="card">
                <div class="card-body">
                    <div class="form-group pb-1">
                        <a href="{{ route('transaction.delivery_order_material.export') }}" class="tl-tip" title="Export to Excel" data-placement="left" data-original-title="Excel">
                            <img src="{{asset('images/excel.png')}}" alt="">
                        </a>
                    </div>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link" id="home-tab" href="{{ route('transaction.delivery_order_material.index') }}" role="tab" aria-controls="home" aria-selected="false">Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" id="document-tab" data-toggle="tab" href="#outstanding" role="tab" aria-controls="outstanding" aria-selected="true">Outstanding</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        @include('transaction::delivery_order_material.entry.tab.outstanding')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection