Modules/Setting/Routes/web.php
<?php

Route::name('setting.')
    ->prefix('setting')
    ->middleware(['impersonate', 'auth'])
    ->group(
        function () {
            Route::get('/', 'SettingController')->name('index');

            Route::resource('users', 'UserController');
            Route::resource('user-type', 'UserTypeController');
            Route::resource('workflow', 'WorkflowController');
            Route::resource('calendar', 'CalendarController');
            Route::resource('exclude-product', 'ExcludeProductController');

            Route::get('reset-password', 'ResetPasswordController@index')->name('reset-password.index');
            Route::post('reset-password', 'ResetPasswordController@store')->name('reset-password.store');
        }
    );

Modules/Setting/Entities/UserType.php
<?php

namespace Modules\Setting\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserType extends Model
{
    use SoftDeletes;
    protected $guarded = [];
}

Modules/Setting/Http/Controllers/UserController.php
<?php

namespace Modules\Setting\Http\Controllers;

use App\User;
use App\Models\Profile;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Modules\Setting\Entities\UserType;
use Modules\Setting\Datatables\UsersDatatable;
use Modules\Setting\Http\Requests\User\CreateRequest;
use Modules\Setting\Http\Requests\User\UpdateRequest;

class UserController extends Controller
{
    public function index(UsersDatatable $datatable)
    {
        $this->hasPermissionTo('view user');
        return $datatable->render('setting::user.index');
    }

    public function create()
    {
        $this->hasPermissionTo('add user');
        return view('setting::user.create', [
            'roles' => Role::get(),
            'types' => UserType::all()
        ]);
    }

    public function store(CreateRequest $request)
    {
        $this->hasPermissionTo('add user');
        $user = User::create([
            'email' => $request->email,
            'username' => $request->username,
            'name' => $request->name,
            'password' => bcrypt($request->password),
            'user_type_id' => $request->user_type_id
        ]);

        Profile::create([
            'user_id' => $user->id,
            'gender' => $request->gender
        ]);

        $roles = $request['roles'];
        if (isset($roles)) {
            foreach ($roles as $role) {
                $role_r = Role::find($role);
                $user->assignRole($role_r);
            }
        }

        flash('Your data has been created')->success();
        return redirect()->route('setting.users.index');
    }

    public function show($id)
    {
        return view('setting::user.show');
    }

    public function edit($id)
    {
        $this->hasPermissionTo('edit user');
        return view('setting::user.edit', [
            'row' => User::find($id),
            'roles' => Role::get(),
            'types' => UserType::all()
        ]);
    }

    public function update(UpdateRequest $request, $id)
    {
        $this->hasPermissionTo('edit user');
        $user = User::find($id);
        $user->fill([
            'name' => $request->name,
            'username' => $request->username,
            'email' => $request->email,
            'user_type_id' => $request->user_type_id
        ]);

        $roles = $request['roles'];
        if (isset($roles)) {
            $user->roles()->sync($roles);
        } else {
            $user->roles()->detach();
        }

        flash('Your data has been updated')->success();
        return redirect()->route('setting.users.index');
    }

    public function destroy($id)
    {
        $this->hasPermissionTo('delete user');
        Profile::whereUserId($id)->delete();
        User::find($id)->delete();

        flash('Your data has been deleted')->error();
        return redirect()->route('setting.users.index');
    }
}

Modules/Setting/Resources/views/user/create.blade.php
@extends('setting::layouts.master')

@section('setting::title', 'Add New User')

@section('setting::breadcrumb-2')
	@include('setting::include.breadcrumb', [
		'title' => 'Users',
		'active' => true,
		'url' => route('setting.users.index')
	])
@endsection

@section('setting::breadcrumb-3')
	@include('setting::include.breadcrumb', [
		'title' => 'New User',
		'active' => false,
	])
@endsection

@section('setting::content')
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-header">
				<h4>Form</h4>
				<div class="card-header-form">
					<a href="{{ route('setting.users.index') }}" class="btn btn-warning">
						<i class="fa fa-arrow-left"></i> Back
					</a>
				</div>
			</div>
			{!! Form::open([
				'route' => 'setting.users.store',
				'onsubmit' => "submitButton.disabled = true"
			]) !!}
				@include('setting::user.form')
			{!! Form::close() !!}
		</div>
	</div>
</div>
@endsection

Modules/Setting/Resources/views/user/edit.blade.php
@extends('setting::layouts.master')

@section('setting::title', 'Edit User')

@section('setting::breadcrumb-2')
	@include('setting::include.breadcrumb', [
		'title' => 'Users',
		'active' => true,
		'url' => route('setting.users.index')
	])
@endsection

@section('setting::breadcrumb-3')
	@include('setting::include.breadcrumb', [
		'title' => 'Edit User',
		'active' => false,
	])
@endsection

@section('setting::content')
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-header">
				<h4>Form</h4>
				<div class="card-header-form">
					<a href="{{ route('setting.users.index') }}" class="btn btn-warning">
						<i class="fa fa-arrow-left"></i> Back
					</a>
				</div>
			</div>

			{!! Form::model($row, [
				'method' => 'PATCH',
				'route' => ['setting.users.update', $row->id],
				'files' => true,
				'onsubmit' => "submitButton.disabled = true"
			]) !!}
				@include('setting::user.form')
			{!! Form::close() !!}
		</div>
	</div>
</div>
@endsection

Modules/Setting/Resources/views/user/form.blade.php
<div class="card-body p-4">
	<div class="row">
		<div class="col-md-6">
			@include('setting::include.input', [
				'type' => 'text',
				'name' => 'name',
				'placeholder' => 'Enter Your name'
			])
		</div>
		<div class="col-md-6">
			@include('setting::include.input', [
				'type' => 'text',
				'name' => 'username',
				'placeholder' => 'Enter Your Username (unique)',
			])
		</div>
		<div class="col-md-6">
			@include('setting::include.input', [
				'type' => 'email',
				'name' => 'email',
				'placeholder' => 'Enter Your Email (unique)',
			])
		</div>
		<div class="col-md-6">
			@include('setting::include.input', [
				'type' => 'password',
				'name' => 'password',
				'placeholder' => 'Enter your password',
				'disabled' => isset($row) ? true : false
			])
		</div>

		<div class="card-header">
			<h4>Roles & Permission</h4>
		</div>

		<div class="col-md-12">
			<div class="form-group">
				@foreach ($roles as $role)
					@isset($row)
						{{ Form::checkbox('roles[]',  $role->id, $row->roles ) }} {{ ucfirst($role->name) }}
				@else
						{{ Form::checkbox('roles[]',  $role->id ) }} {{ ucfirst($role->name) }}
					@endif
				@endforeach
			</div>
		</div>

		<div class="col-md-12">
			@include('setting::include.select', [
				'name' => 'user_type_id',
				'title' => 'User Type',
				'options' => $types->pluck('name', 'id')
			])
		</div>

		@if(!isset($row))
		<div class="card-header">
			<h4>Profile</h4>
		</div>

		<div class="col-md-12">
			@include('setting::include.select', [
				'name' => 'gender',
				'options' => [
					'' => 'Please Select',
					'0' => 'Female',
					'1' => 'Male'
				]
			])
		</div>
		@endisset
	</div>
</div>
@include('setting::include.button')

Modules/Setting/Resources/views/user/index.blade.php
@extends('setting::layouts.master')

@section('setting::title', 'Users')

@section('setting::breadcrumb-2')
	@include('setting::include.breadcrumb', [
		'title' => 'Setting',
		'active' => true,
		'url' => route('setting.index')
	])
@endsection

@section('setting::breadcrumb-3')
@include('setting::include.breadcrumb', [
'title' => 'Users',
'active' => false,
])
@endsection

@section('setting::content')
<div class="row">
	<div class="col-12">

		@include('flash::message')

		<div class="card">
			<div class="card-header">
				<h4>Users List</h4>
				<div class="card-header-form">
					<a href="{{ route('setting.users.create') }}" class="btn btn-primary">
						<i class="fa fa-plus"></i> Add new
					</a>
				</div>
			</div>
			<div class="card-body p-4">
				<div class="table-responsive">
					{!! $dataTable->table(['class' => 'table table-bordered table-hover table-stripped']) !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@push('javascript')
@include('shared.wrapperDatatable')
@endpush