Modules/Procurement/Routes/web.php
            Route::resource('weight_class', 'WeightClassController');
            Route::get('/showPurchaseInvoice/{id}', 'SupplierController@showPurchaseInvoice')->name('supplier.showPurchaseInvoice');
            Route::resource('product', 'ProductController');
            Route::post('product/subCategory', 'ProductController@subCategory')->name('product.sub-category');
            Route::get('/{id}/showSO', 'ProductController@showSO')->name('product.showSO');
            Route::resource('customer', 'CustomerController');
            Route::put('/{id}/customer', 'CustomerController@saveDocument')->name('customer.document');
            Route::put('/{id}/supplier', 'SupplierController@saveDocument')->name('supplier.document');
            Route::get('/{id}/showInvoice', 'CustomerController@showInvoice')->name('customer.showInvoice');
            Route::get('/{id}/showPr', 'ProductController@showPr')->name('product.showPr');
            Route::get('/{id}/showSo', 'ProductController@showSo')->name('product.showSo');
            Route::resource('price_category', 'PriceCategoryController');
            Route::resource('tax', 'TaxController');
            Route::resource('payment_term', 'PaymentTermController');
            Route::resource('depot_master', 'WarehouseMasterController');
            Route::resource('currency', 'CurrencyController');
            Route::resource('payment_method', 'PaymentMethodController');
            Route::resource('vehicle', 'VehicleController');
            Route::resource('product_sub_category', 'ProductSubCategoryController');
            Route::resource('product_price', 'ProductPriceController');
            Route::get('/{id}/duplicate', 'ProductPriceController@duplicate')->name('product_price.duplicate');
            Route::resource('business_role', 'BusinessRoleController');
            Route::resource('business_industry', 'BusinessIndustryController');
            Route::resource('project', 'ProjectController');
            Route::get('showSO/{id}', 'ProjectController@showSO')->name('project.showSO');
        });
    });

    Route::resource('report', 'ReportController');
    Route::resource('account-payable', 'AccountPayableController');
    Route::get('account-payable-report', 'AccountPayableController@report')->name('account-payable-report');
    Route::get('/account-payable-report-detail/{id}', 'AccountPayableController@reportDetail')->name('account-payable-report-detail');
    Route::resource('account_payable_aging', 'AccountPayableAgingController');

    Route::resource('purchase_invoice', 'PurchaseInvoiceController');
    Route::get('purchase_invoice_outstanding', 'PurchaseInvoiceController@outstanding')->name('purchase_invoice_outstanding');
    Route::get('purchase_invoice/pdf/{id}', 'PurchaseInvoiceController@pdf')->name('purchase_invoice.pdf');
    Route::get('purchase_invoice/payment-history/{id}', 'PurchaseInvoiceController@fetchPartial')->name('purchase_invoice.payment-history');
    Route::get('purchase_invoice/receivable_form/{id}', 'PurchaseInvoiceController@receiveForm')->name('purchase_invoice.receivable_form');
    Route::get('purchase_invoice_report', 'PurchaseInvoiceController@report')->name('purchase_invoice.report.index');
    Route::get('/showPurchaseReturn/{id}', 'PurchaseInvoiceController@showPurchaseReturn')->name('purchase_invoice.showPurchaseReturn');

    Route::resource('purchase_receipt', 'PurchaseReceiptController');
    Route::get('purchase_receipt_outstanding', 'PurchaseReceiptController@outstanding')->name('purchase_receipt_outstanding');
    Route::get('purchase_receipt/pdf/{id}', 'PurchaseReceiptController@pdf')->name('purchase_receipt.pdf');
    Route::get('purchase_receipt/payment-history/{id}', 'PurchaseReceiptController@fetchPartial')->name('purchase_receipt.payment-history');
    Route::get('purchase_receipt/receivable_form/{id}', 'PurchaseReceiptController@receiveForm')->name('purchase_receipt.receivable_form');
    Route::get('purchase_receipt_report', 'PurchaseReceiptController@report')->name('purchase_receipt.report.index');

    Route::resource('purchase-return', 'PurchaseReturnController');
    Route::get('/{id}/adjustment', 'PurchaseReturnController@adjustment')->name('purchase_return.showAdjustment');
    Route::post('adjustment', 'PurchaseReturnController@saveAdjustment')->name('purchase_return.adjustment');
    Route::get('purchase-return-report', 'PurchaseReturnController@report')->name('purchase-return-report');
    Route::get('/purchase-return-report-detail/{id}', 'PurchaseReturnController@reportDetail')->name('purchase-return-report-detail');

    Route::name('purchase_requisition.')->prefix('purchase_requisition')->namespace('PurchaseRequisition')->group(function () {
        Route::put('/{id}', 'PurchaseRequisitionController@update')->name('update');
        Route::get('view', 'ViewController')->name('view');
        Route::resource('/', 'PurchaseRequisitionController', ['except' => ['update', 'destroy', 'edit']]);
        Route::get('/{id}/detail', 'PurchaseRequisitionController@detail')->name('detail');
        Route::get('/{id}/report-detail', 'PurchaseRequisitionController@detailReport')->name('report-detail');
        Route::get('/{id}/edit', 'PurchaseRequisitionController@edit')->name('edit');
        Route::get('/{id}/show', 'PurchaseRequisitionController@show')->name('show');
        Route::delete('/{id}', 'PurchaseRequisitionController@destroy')->name('destroy');
        Route::post('attachment', 'PurchaseRequisitionController@saveAttachment')->name('attachment');

        Route::get('/department', 'PurchaseRequisitionController@department')->name('department');

        Route::get('/costCenter', 'PurchaseRequisitionController@costCenter')->name('costCenter');
        Route::get('/product', 'PurchaseRequisitionController@product')->name('product');
        Route::get('product-detail/{id}', 'PurchaseRequisitionController@productDetail')->name('product-detail');

        Route::get('/uom', 'PurchaseRequisitionController@uom')->name('uom');
        Route::get('/export', 'PurchaseRequisitionController@export')->name('export');

        Route::resource('approval', 'PurchaseRequisitionApprovalController');
        Route::get('report', 'PurchaseRequisitionController@report')->name('report');
        Route::get('/{id}/prDetail', 'PurchaseRequisitionController@getPrDetail')->name('prDetail');
        Route::get('/{id}/pdf', 'PurchaseRequisitionController@pdf')->name('pdf');
    });

    Route::name('purchase-order.')->prefix('purchase-order')->namespace('PurchaseOrder')->group(function () {
        Route::put('/{id}', 'PurchaseOrderController@update')->name('update');
        Route::get('view', 'ViewPurchaseOrderController')->name('view');
        Route::get('/{id}/edit', 'PurchaseOrderController@edit')->name('edit');

        Route::resource('/', 'PurchaseOrderController', ['except' => ['update', 'destroy', 'edit']]);
        Route::get('/export', 'PurchaseOrderController@export')->name('export');
        Route::get('/{id}/show', 'PurchaseOrderController@show')->name('show');
        Route::get('detail-modal/{id}', 'PurchaseOrderController@detailModal')->name('detail-modal');
        Route::post('attachment', 'PurchaseOrderController@saveAttachment')->name('attachment');
        Route::get('accept/{id}', 'PurchaseOrderController@accept')->name('accept');
        Route::post('saveAccept', 'PurchaseOrderController@saveAccept')->name('saveAccept');

        Route::get('/{id}/detail', 'PurchaseOrderController@detail')->name('detail');
        Route::get('/{id}/pdf', 'PurchaseOrderController@pdf')->name('pdf');
        Route::get('/{id}/edit', 'PurchaseOrderController@edit')->name('edit');
        Route::delete('/{id}', 'PurchaseOrderController@destroy')->name('destroy');
        Route::get('/get-po', 'PurchaseOrderController@purchaseOrder')->name('get-po');
        Route::get('/supplier', 'PurchaseOrderController@supplier')->name('supplier');
        Route::get('/supplier-detail', 'PurchaseOrderController@supplierDetail')->name('supplier-detail');


        Route::resource('approval', 'PurchaseOrderApprovalController');
        Route::get('report', 'PurchaseOrderController@report')->name('report');
        Route::get('/{id}/report-detail', 'PurchaseOrderController@detailReport')->name('report-detail');
    });

    Route::name('ap_credit_debit_note.')->prefix('ap_credit_debit_note')->group(function () {
        Route::resource('/', 'APCreditDebitNoteController');
        Route::get('/{id}/edit', 'APCreditDebitNoteController@edit')->name('edit');
        Route::put('/{id}', 'APCreditDebitNoteController@update')->name('update');
        Route::post('transaction/ap-credit-debit-note/payable', 'APCreditDebitNoteController@getPayable')->name('getPayable');
        Route::delete('/{id}', 'APCreditDebitNoteController@destroy')->name('destroy');
        Route::get('report', 'APCreditDebitNoteController@report')->name('report');
        Route::get('detail/{id}', 'APCreditDebitNoteController@reportDetail')->name('report-detail');
    });


    Route::name('debit_note.')->prefix('debit_note')->group(function () {
        Route::resource('/', 'DebitNoteController');
        Route::get('/{id}/edit', 'DebitNoteController@edit')->name('edit');
        Route::put('/{id}', 'DebitNoteController@update')->name('update');
        // Route::post('procurement/debit-note/payable', 'CreditNoteController@getPayable')->name('getPayable');
        Route::delete('/{id}', 'DebitNoteController@destroy')->name('destroy');
        Route::get('report', 'DebitNoteController@report')->name('report');
        Route::get('detail/{id}', 'DebitNoteController@reportDetail')->name('report-detail');
    });

    Route::resource('voucher', 'Voucher\\VoucherController');
    Route::get('template-voucher','Voucher\\VoucherController@templateVoucher')->name('voucher.template-voucher');

Modules/Procurement/Entities/PurchaseRequisition.php
<?php

namespace Modules\Procurement\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\HR\Entities\CostCenter;
use Modules\HR\Entities\Department;
use Modules\HR\Entities\Employee;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class PurchaseRequisition extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    protected $guarded = [];

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }


    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function costCenter()
    {
        return $this->belongsTo(CostCenter::class);
    }

    public function items()
	{
		return $this->hasMany(PurchaseRequisitionItem::class, 'purchase_requisition_id');
	}

    public function latestApprove()
    {
        return $this->belongsTo(Employee::class, 'latest_approver');
    }

    public function approveToGo()
    {
        return $this->belongsTo(Employee::class, 'approver_to_go');
    }

    public function rejectedBy()
    {
        return $this->belongsTo(Employee::class, 'rejected_by');
    }
    public function project()
    {
        return $this->belongsTo(Project::class, 'project_id');
    }
}

Modules/Procurement/Http/Controllers/Api/PurchaseRequisitionController.php
<?php

namespace Modules\Procurement\Http\Controllers\Api;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Procurement\Entities\PurchaseRequisition;
use Modules\Procurement\Entities\PurchaseRequisitionItem;

class PurchaseRequisitionController extends Controller
{
    public function edit($id)
	{
		return PurchaseRequisition::with(['department', 'costCenter', 'items', 'items.product', 'items.uom', 'project'])->find($id);
	}

    public function removeItem($id)
	{
		PurchaseRequisitionItem::find($id)->forceDelete();
		return response()->json([
			'success' => true
		]);
	}
}

Modules/Procurement/Http/Controllers/PurchaseRequisition/PurchaseRequisitionApprovalController.php
<?php

namespace Modules\Procurement\Http\Controllers\PurchaseRequisition;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Modules\HR\Entities\Employee;
use Modules\Procurement\Entities\PurchaseRequisition;
use Modules\Procurement\Entities\PurchaseRequisitionItem;
use Modules\Procurement\Entities\PurchaseRequisitionApproval;
use Modules\Procurement\DataTables\PurchaseRequisitionApprovalDatatable;

class PurchaseRequisitionApprovalController extends Controller
{
    public function index(PurchaseRequisitionApprovalDatatable $datatable)
    {
        $this->hasPermissionTo('view purchase requisition approval');

        $employee = Employee::where('user_id', auth()->user()->id)->first();
        if (empty($employee)){
            flash('Ops.. please check your employee id.')->error();
            return back();
        }
        
        $purchaseRequisitions = filterModuleByStatus(PurchaseRequisition::class, [
            'employee', 'department', 'costCenter'
        ]);
        
        return $datatable->render('procurement::purchase_requisition.approval.index', compact('purchaseRequisitions'));
    }


    public function show($id)
    {
        $this->hasPermissionTo('view purchase requisition approval');

        $row = PurchaseRequisition::findOrFail($id);
        $items = PurchaseRequisitionItem::where('purchase_requisition_id', $id)->get();
        $histories = PurchaseRequisitionApproval::where('purchase_requisition_id', $id)
            ->get()
            ->sortBy('id');
        if($row){
            $media = $row->getMedia('purchase_requisition') ?? [];
        }else{
            $media = [];
        }

        return view('procurement::purchase_requisition.approval.modals.detail', compact('row', 'items','histories','media'));
    }

    public function update(Request $request, $id)
    {
        $this->hasPermissionTo('edit purchase requisition approval');

        $description = request('description');
        if (request()->has('approve')) {
            \Approval::action(PurchaseRequisition::class, PurchaseRequisitionApproval::class, $id, 'purchase_requisition_id', $description);
        } else {
            \Approval::reject(PurchaseRequisition::class, PurchaseRequisitionApproval::class, $id, 'purchase_requisition_id', $description);
        }

        flash('Your entry has been updated successfully')->success();
        return back();
    }
}

Modules/Procurement/Http/Controllers/PurchaseRequisition/ViewController.php
<?php

namespace Modules\Procurement\Http\Controllers\PurchaseRequisition;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class ViewController extends Controller
{
    public function __invoke()
    {
        return view('procurement::purchase_requisition.index');
    }
}

Modules/Procurement/Resources/views/purchase_requisition/approval/index.blade.php
@extends('procurement::layouts.app')

@section('procurement::title', 'PR Approval')

@section('procurement::breadcrumb-2')
    @include('procurement::include.breadcrum', [
    'title' => 'Procurement',
    'active' => true,
    'url' => route('procurement.view')
    ])
@endsection

@section('procurement::breadcrumb-3')
    @include('procurement::include.breadcrum', [
    'title' => 'PR Approval',
    'active' => true,
    'url' => route('procurement.purchase_requisition.approval.index')
    ])
@endsection

@section('procurement::content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Approval</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">History</a>
                    </li>
                </ul>
            </div>
            <div class="card-body p-0">
                @include('flash::message')
                <div class="tab-content" id="myTabContent">
                     <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="table-responsive">
                            <table class="table table-striped" id="sortable-table">
                                <thead>
                                <tr class="text-center">
                                    <th class="text-center">
                                        <i class="fas fa-th"></i>
                                    </th>
                                    <th>Code Number</th>
                                    <th>Created By</th>
                                    <!-- <th>Title</th> -->
                                    <th>Submission Date</th>
                                    <th>Requested Date</th>
                                    <!-- <th>Department</th> -->
                                   {{--  <th>Cost Center</th> --}}
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach($purchaseRequisitions as $row)
                                    <tr class="text-center">
                                        <td>
                                            <div class="sort-handler">
                                                <i class="fas fa-th"></i>
                                            </div>
                                        </td>
                                        <td>{{ $row['code_number'] }}</td>
                                        <td>{{ $row['employee']['name'] }}</td>
                                        <!-- <td>{{ $row['title'] }}</td> -->
                                        <td>{{ format_d_month_y($row['submission_date']) }}</td>
                                        <td>{{ format_d_month_y($row['required_date']) }}</td>
                                        <!-- <td>{{ $row['department']['name'] }}</td> -->
                                        {{-- <td>{{ $row['cost_center']['name'] }}</td> --}}
                                        <td>
                                            <a href="{{ route('procurement.purchase_requisition.approval.show', $row['id']) }}" class="btn btn-info modal-global">
                                                Detail
                                            </a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="card-body p-10">
                            <div class="table-responsive">
                                {!! $dataTable->table() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('javascript')
    @include('shared.wrapperDatatable')
    @include('procurement::purchase_requisition.approval.modals.index')
    <script>
        // show detail data in modal
        $('.modal-global').click(function(event) {
            event.preventDefault();

            var url = $(this).attr('href');

            $("#modal-global").modal('show');

            $.ajax({
                url: url,
                type: 'GET',
                dataType: 'html',
            })
                .done(function(response) {
                    $("#modal-global").find('.modal-body').html(response);
                });

        });
    </script>
@endpush